### ISSUE TITLE
[ERROR] 163: Expecting value: line 4 column 1 (char 3)

### ISSUE THREAD

**Issue by HalloweenMagic** [coskundeniz/ad_clicker#10]
Running this command:

`python run_ad_clicker.py -qf queries.txt -pf proxies.txt -ms 1
`

Or also:

`python run_ad_clicker.py -qf queries.txt -pf proxies.txt
`

The script seems to fail to interact with the browser

![2022-12-27_131854](https://user-images.githubusercontent.com/67958671/209667375-ac9bd34f-b025-4cac-99c3-881173d981cc.jpg)

Also, checking "What is my IP" inside opened browser, the proxy doesn't work (as I can see my real IP)

**Comment by coskundeniz** [comment]
I will check this out.

**Comment by coskundeniz** [comment]
@HalloweenMagic  I fixed get_location and proxy usage without authentication. Proxies with authentication have still issue.
Can you try with the latest version?

**Comment by coskundeniz** [comment]
Fixed proxy with authentication issue.
