### ISSUE TITLE
error in line 6 proxy.py

### ISSUE THREAD

**Issue by kimimartin** [coskundeniz/ad_clicker#12]
When trying to run a test it throws me this error
`(env) (root) D:\Descargas\ad_clicker-main (1)\ad_clicker-main>python ad_clicker.py -q "wireless keyboard" -pf ~/proxies.txt
Traceback (most recent call last):
  File "ad_clicker.py", line 5, in <module>
    from proxy import get_proxies
  File "D:\Descargas\ad_clicker-main (1)\ad_clicker-main\proxy.py", line 6, in <module>
    def get_proxies(proxy_file: Path) -> list[str]:
TypeError: 'type' object is not subscriptable`

My python version 3.9.5

**Comment by coskundeniz** [comment]
list should be valid after version 10. Make the followings:
```
from typing import List
change list[str] to List[str]
```
