### ISSUE TITLE
Multi Browser not working

### ISSUE THREAD

**Issue by Taner42** [coskundeniz/ad_clicker#13]
(env) PS C:\Users\Administrator\Desktop\ad_clicker-main> py ad_clicker.py -q "wireless keyboard"
01-03-2023 16:11:30 [ INFO]  58: Starting search for 'wireless keyboard'
01-03-2023 16:11:35 [ INFO]  76: Getting ad links...
01-03-2023 16:14:16 [ INFO] 192: ======= Found an Ad =======
01-03-2023 16:14:16 [ INFO] 192: ======= Found an Ad =======
01-03-2023 16:14:16 [ INFO] 192: ======= Found an Ad =======
01-03-2023 16:14:16 [ INFO] 192: ======= Found an Ad =======
01-03-2023 16:14:16 [ INFO] 192: ======= Found an Ad =======
01-03-2023 16:14:16 [ INFO]  85: Found 5 ads
01-03-2023 16:14:16 [ INFO]  99: Clicking to [Wireless Keyboards on Amazon - Low Priced Wireless Keyboards](https://www.amazon.com/wireless-keyboards/s?k=wireless+keyboards)...
01-03-2023 16:14:21 [ INFO]  99: Clicking to [Washable & Waterproof Keyboards – Seal Shield](https://sealshield.com/washable-waterproof-keyboards/)...
01-03-2023 16:14:26 [ INFO]  99: Clicking to [Keyboards](https://mygamerspot.com/collections/keyboards)...
01-03-2023 16:14:31 [ INFO]  99: Clicking to [Wireless Keyboard at Amazon® - Amazon Official Site](https://www.amazon.com/wireless-keyboard/s?k=wireless+keyboard)...
01-03-2023 16:14:37 [ INFO]  99: Clicking to [Shop Keyboard & Mouse - For PC, Laptop, Multi Devices](https://www.seenda.com/)...
(env) PS C:\Users\Administrator\Desktop\ad_clicker-main> py run_ad_clicker.py -qf \Users\Administrator\Desktop\ad_clicker-main/queries.txt -pf \Users\Administrator\Desktop\ad_clicker-main/proxies.txt -ms 2
01-03-2023 16:18:21 <<2>> [ INFO] 218: Using proxy: 'reveriespotter0m:D66bVoCXVy:204.242.180.208:49036'
01-03-2023 16:18:21 <<1>> [ INFO] 218: Using proxy: 'reveriespotter0m:D66bVoCXVy:204.242.180.208:49036'
01-03-2023 16:18:21 <<4>> [ INFO] 218: Using proxy: 'reveriespotter0m:D66bVoCXVy:204.242.180.208:49036'
01-03-2023 16:18:21 <<3>> [ INFO] 218: Using proxy: 'reveriespotter0m:D66bVoCXVy:204.242.180.208:49036'
01-03-2023 16:18:24 <<2>> [ INFO]  81: Connecting with IP: 'reveriespotter0m
01-03-2023 16:18:24 <<2>> [ERROR] 119: Expecting value: line 4 column 1 (char 3)
01-03-2023 16:18:24 <<4>> [ INFO]  81: Connecting with IP: 'reveriespotter0m
01-03-2023 16:18:24 <<3>> [ INFO]  81: Connecting with IP: 'reveriespotter0m
01-03-2023 16:18:24 <<4>> [ERROR] 119: Expecting value: line 4 column 1 (char 3)
01-03-2023 16:18:24 <<3>> [ERROR] 119: Expecting value: line 4 column 1 (char 3)
01-03-2023 16:18:25 <<1>> [ INFO]  81: Connecting with IP: 'reveriespotter0m
01-03-2023 16:18:25 <<1>> [ERROR] 119: Expecting value: line 4 column 1 (char 3)
01-03-2023 16:18:25 <<2>> [ERROR] 119: Expecting value: line 4 column 1 (char 3)
01-03-2023 16:18:26 <<4>> [ERROR] 119: Expecting value: line 4 column 1 (char 3)
01-03-2023 16:18:26 <<3>> [ERROR] 119: Expecting value: line 4 column 1 (char 3)
01-03-2023 16:18:26 <<1>> [ERROR] 119: Expecting value: line 4 column 1 (char 3)
01-03-2023 16:18:26 <<2>> [ERROR] 119: Expecting value: line 4 column 1 (char 3)
01-03-2023 16:18:27 <<4>> [ERROR] 119: Expecting value: line 4 column 1 (char 3)
01-03-2023 16:18:27 <<3>> [ERROR] 119: Expecting value: line 4 column 1 (char 3)
01-03-2023 16:18:27 <<1>> [ERROR] 119: Expecting value: line 4 column 1 (char 3)
01-03-2023 16:18:27 <<2>> [ERROR] 119: Expecting value: line 4 column 1 (char 3)
01-03-2023 16:18:28 <<4>> [ERROR] 119: Expecting value: line 4 column 1 (char 3)
01-03-2023 16:18:28 <<3>> [ERROR] 119: Expecting value: line 4 column 1 (char 3)
01-03-2023 16:18:28 <<1>> [ERROR] 119: Expecting value: line 4 column 1 (char 3)
01-03-2023 16:18:29 <<4>> [ERROR] 119: Expecting value: line 4 column 1 (char 3)
01-03-2023 16:18:29 <<2>> [ERROR] 119: Expecting value: line 4 column 1 (char 3)
01-03-2023 16:18:29 <<3>> [ERROR] 119: Expecting value: line 4 column 1 (char 3)
01-03-2023 16:18:29 <<1>> [ERROR] 119: Expecting value: line 4 column 1 (char 3)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\ad_clicker-main\ad_clicker.py", line 92, in <module>
    main()
  File "C:\Users\Administrator\Desktop\ad_clicker-main\ad_clicker.py", line 77, in main
    driver = create_webdriver(proxy, args.auth, args.headless)
  File "C:\Users\Administrator\Desktop\ad_clicker-main\utils.py", line 243, in create_webdriver
    lat, long = get_location(geolocation_db_client, proxy, auth)
  File "C:\Users\Administrator\Desktop\ad_clicker-main\utils.py", line 128, in get_location
    if not (latitude or longitude):
UnboundLocalError: local variable 'latitude' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\ad_clicker-main\ad_clicker.py", line 92, in <module>
    main()
  File "C:\Users\Administrator\Desktop\ad_clicker-main\ad_clicker.py", line 77, in main
    driver = create_webdriver(proxy, args.auth, args.headless)
  File "C:\Users\Administrator\Desktop\ad_clicker-main\utils.py", line 243, in create_webdriver
    lat, long = get_location(geolocation_db_client, proxy, auth)
  File "C:\Users\Administrator\Desktop\ad_clicker-main\utils.py", line 128, in get_location
    if not (latitude or longitude):
UnboundLocalError: local variable 'latitude' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\ad_clicker-main\ad_clicker.py", line 92, in <module>
    main()
  File "C:\Users\Administrator\Desktop\ad_clicker-main\ad_clicker.py", line 77, in main
    driver = create_webdriver(proxy, args.auth, args.headless)
  File "C:\Users\Administrator\Desktop\ad_clicker-main\utils.py", line 243, in create_webdriver
    lat, long = get_location(geolocation_db_client, proxy, auth)
  File "C:\Users\Administrator\Desktop\ad_clicker-main\utils.py", line 128, in get_location
    if not (latitude or longitude):
UnboundLocalError: local variable 'latitude' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\ad_clicker-main\ad_clicker.py", line 92, in <module>
    main()
  File "C:\Users\Administrator\Desktop\ad_clicker-main\ad_clicker.py", line 77, in main
    driver = create_webdriver(proxy, args.auth, args.headless)
  File "C:\Users\Administrator\Desktop\ad_clicker-main\utils.py", line 243, in create_webdriver
    lat, long = get_location(geolocation_db_client, proxy, auth)
  File "C:\Users\Administrator\Desktop\ad_clicker-main\utils.py", line 128, in get_location
    if not (latitude or longitude):
UnboundLocalError: local variable 'latitude' referenced before assignment

**Comment by coskundeniz** [comment]
You should check the documentation better. run_ad_clicker is used for this.

Run multiple browsers by taking queries and proxies with authentication from the given files.

    python run_ad_clicker.py -qf ~/queries.txt --auth -pf ~/proxies.txt
