### ISSUE TITLE
Mobile accept cookies not works

### ISSUE THREAD

**Issue by Seeoos** [coskundeniz/ad_clicker#15]
Hi,

I appreciate your works, there is a issue if have a mobile useragent , is stopped on the cookies accept, can you please fix this

thanks

**Comment by Seeoos** [comment]
<img width="515" alt="Capture" src="https://user-images.githubusercontent.com/126768414/222518241-bcd44c72-b24b-4dc0-8430-53202f15aa36.PNG">

**Comment by Seeoos** [comment]
<img width="511" alt="Capture" src="https://user-images.githubusercontent.com/126768414/222518377-e08110b6-54d2-4a0c-8706-7c40eeb5e2e9.PNG">

**Comment by coskundeniz** [comment]
@Seeoos I updated the cookie dialog closing. Can you check and let me know? Thank you.

**Comment by HalloweenMagic** [comment]
> @Seeoos I updated the cookie dialog closing. Can you check and let me know? Thank you.

Yes, now it's working
