### ISSUE TITLE
run_ad_clicker.py issues

### ISSUE THREAD

**Issue by HalloweenMagic** [coskundeniz/ad_clicker#16]
Hi!
If I use the "basic" ad_clicker.py everything is working fine.
For example:

`python ad_clicker.py -q "test" -t 15`
`python ad_clicker.py -q "test@domain1#domain2#domain3" -t 15`

When I try to automize the script using run_ad_clicker.py nothing works.
For example, if I use this command on Windows:

`py run_ad_clicker.py -qf queries.txt -pf proxies.txt`

As you can see in the screenshot below, the script generate a lot of errors and nothing works

![Error2](https://user-images.githubusercontent.com/67958671/225033444-bf4c2687-b6a2-484b-9ea9-1765498c8241.jpg)

This is the content of "queries.txt":

`"test@name1#name2#name3"`
`"test2@name1#name2#name3"`

**Comment by coskundeniz** [comment]
From the unrecognized characters at the end of the proxy outputs, there can be an encoding issue in your files. Also, you don't need to use quotes in file. Single query/proxy for each line is sufficient.

**Comment by HalloweenMagic** [comment]
> From the unrecognized characters at the end of the proxy outputs, there can be an encoding issue in your files. Also, you don't need to use quotes in file. Single query/proxy for each line is sufficient.

Thanks for your reply.
I don't use any quotes in the file.
This is the content of "proxies.txt":

`bcjeabam:password@185.199.229.156:7492`
`bcjeabam:password@185.199.228.220:7300`

![Proxies](https://user-images.githubusercontent.com/67958671/225055290-9e0ea005-c0e3-4d20-af34-f615cfb69812.jpg)

**Comment by coskundeniz** [comment]
Since I can't reproduce it on my side, we should check it on your computer. If you want to try over a Zoom call, please send me an email. Thank you.
