### ISSUE TITLE
Geolocation Permission

### ISSUE THREAD

**Issue by ebulku** [coskundeniz/ad_clicker#18]
I want to Allow Location Permissions so it will take the latitude and longitude from the proxy. I have tried different settings, but the popup to Allow or Block the Permissions is still showing in chrome. Do you know any way to Allow it by default? This is what I am using now, but is not working:

```
driver.execute_cdp_cmd(
    "Browser.grantPermissions",
    {
      "origin": "https://www.google.com",
      "permissions": ["geolocation"]
    },
)
```

**Comment by ebulku** [comment]
I have tried also adding it in the options:

```
prefs = {"profile.default_content_settings.geolocation": 1}
chrome_options.add_experimental_option("prefs", prefs)
```

**Comment by coskundeniz** [comment]
I am already setting the geolocation according to IP address.


```
# set geolocation of the browser according to IP address
      accuracy = 90
      lat, long = get_location(geolocation_db_client, proxy, auth)

      if lat and long:
          driver.execute_cdp_cmd(
              "Emulation.setGeolocationOverride",
              {"latitude": lat, "longitude": long, "accuracy": accuracy},
          )
```

You can check the utils.py module. Do you mean something else?

**Comment by coskundeniz** [comment]
@ebulku 
You can also check this page: https://testingbot.com/support/selenium/permission-popups

**Comment by ebulku** [comment]
I have tested some proxies, and the location is not the same as the one set by `Emulation.setGeolocationOverride`. But there is a way for that to be updated, you have to click on the button "Update location" in the footer of the search result page. But for that to work you have to enable Location. And this popup is keep showing even after I added the option to enable the geolocation by default.

![image](https://user-images.githubusercontent.com/11932725/234898142-945cfe45-39de-4625-a29b-f155b874b781.png)

**Comment by ebulku** [comment]
This was related to incognito too. After removing incognito it is working.
