### ISSUE TITLE
Proxy not being activated in the first run

### ISSUE THREAD

**Issue by ebulku** [coskundeniz/ad_clicker#19]
I am using a proxy and having a breakpoint as soon as the page is loaded. When the page is loaded, it is showing the language of my PC IP, you can check that also from the Swedish Language. The same ip is also after a reload. But if you visit the Extentions, and get back to a new tab, it is showing the proxy, in this case, Italian IP.

**Comment by coskundeniz** [comment]
What do you see when you run the following line in `_load` method? Your IP or proxy IP? 

`self._driver.get("https://whatismyipaddress.com/")`

If it is possible with your provider, also try proxy format in **username:password@host:port** without **;** characters.

**Comment by coskundeniz** [comment]
You can try removing the `incognito` option in `utils.py`.

**Comment by ebulku** [comment]
It was related to incognito, after removing it, proxy looks ok!
Thank you for the great work.

**Comment by coskundeniz** [comment]
I made the incognito mode optional.
