### ISSUE TITLE
error cannot use it. 

### ISSUE THREAD

**Issue by Daniel3356** [coskundeniz/ad_clicker#2]
Hi can you please put a step by step instructions on how to install it I have trouble installing it. 
this is that I have as an error: 
```
(ad_clicker) name@ubuntu-linux:~$ python ad_clicker/ad_clicker.py -q "keyword"
Traceback (most recent call last):
  File "ad_clicker/ad_clicker.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```
Thanks for making a step my step and Thanks for helping me.

**Comment by coskundeniz** [comment]
> ModuleNotFoundError: No module named 'requests'

It means requests package is not installed. Please first run the setup script as explained in description.
