### ISSUE TITLE
Using the Run_in_loop - Cant find files

### ISSUE THREAD

**Issue by SmallCoffeeCup** [coskundeniz/ad_clicker#22]
Hi!

I am having an issue when using the "run in loop function". It says my there is no such file in the directory when it clearly is. 

PS C:\Users\Small Coffee\Documents\ad_clicker> python run_in_loop.py -qf queries.txt -pf proxies2.txt --auth 
26-05-2023 15:45:48 [ INFO]  98: Running with 8 browsers...
python: can't open file 'C:\\Users\\SCC': [Errno 2] No such file or directory
python: can't open file 'C:\\Users\\SCC': [Errno 2] No such file or directory
python: can't open file 'C:\\Users\\SCC': [Errno 2] No such file or directory
python: can't open file 'C:\\Users\\SCC': [Errno 2] No such file or directory
python: can't open file 'C:\\Users\\SCC': [Errno 2] No such file or directory
python: can't open file 'C:\\Users\\SCC': [Errno 2] No such file or directory
python: can't open file 'C:\\Users\\SCC': [Errno 2] No such file or directory
python: can't open file 'C:\\Users\\SCC': [Errno 2] No such file or directory

What is interesting is the command below will run no problem, so it looks like it is having trouble locating the queries file, but it is in the directory folder.

PS C:\Users\Small Coffee\Documents\ad_clicker> python ad_clicker.py -q "wireless keyboard" -t 5 --auth -pf proxies2.txt -e "amazon"

please advise

**Comment by coskundeniz** [comment]
Is there a directory as "C:\Users\SCC"? If there is, and there is a space after that you can try renaming the directory with no space. You can also try giving full file paths inside quotes.

**Comment by SmallCoffeeCup** [comment]
So I tried specifying the direct file path in both "" and '' and still no go - looks like it could be an issue with the space in the directory? This is the user login and cant be changed. Any other ideas? 

python run_in_loop.py -qf 'C:\Users\Small Coffee\Documents\ad_clicker-1.0.3\queries.txt' -pf 'C:\Users\Small Coffee\Documents\ad_clicker-1.0.3\proxies2.txt' --auth

**Comment by coskundeniz** [comment]
You can reserve a slot from the following link and we can take a look.
https://calendly.com/coskundeniz/30min

**Comment by coskundeniz** [comment]
Fixed with v1.0.4
Thank you for the help.
