### ISSUE TITLE
captcha google

### ISSUE THREAD

**Issue by rangergamerxx** [coskundeniz/ad_clicker#25]
Hello Deniz..
That posible to add captcha solver on your bot?
for example using 2captcha api to solved it

**Comment by coskundeniz** [comment]
Hi,
I will try adding it to the premium version in the future. For now, the best way is to change the proxy, or even better but more expensive is using the residential proxies. Thanks.

**Comment by rangergamerxx** [comment]
Thank you Deniz.
I'll wait for your premium bot :)

**Comment by sajjadsaharkhan** [comment]
> Hi, I will try adding it to the premium version in the future. For now, the best way is to change the proxy, or even better but more expensive is using the residential proxies. Thanks.

What proxy provider do you recommend?
Of course, except for the tor

**Comment by coskundeniz** [comment]
@rangergamerxx captcha integration was added to premium version. I forgot to remind you.
@sajjadsaharkhan I can't recommend any, but I use the most basic version from webshare. You can also check the geonode.
I think the most affordable way is to use regular proxies and 2captcha service(about $3 for 1000 solved captchas).

**Comment by sajjadsaharkhan** [comment]
> @rangergamerxx captcha integration was added to premium version. I forgot to remind you. @sajjadsaharkhan I can't recommend any, but I use the most basic version from webshare. You can also check the geonode. I think the most affordable way is to use regular proxies and 2captcha service(about $3 for 1000 solved captchas).

thanks for your answer.
tor is good high-scale use? I want to run bot with 8 concurrent browsers 300 times :)
what is your suggestion for this scale? (recommendation about proxy providing)

I used Tor according to your article, but every time I get a 403 error, even after changing the IP, I get this error.

**Comment by coskundeniz** [comment]
@sajjadsaharkhan 
Note that this tool does not use tor anymore since the tor exit nodes are publicly known. You need a machine with at least 8 cpu cores and 16 GB of ram to run 7-8 browsers. 
I mentioned about proxy providers in the previous answer.
Thanks.
