### ISSUE TITLE
No module named 'psutil' on python run_in_loop.py

### ISSUE THREAD

**Issue by HalloweenMagic** [coskundeniz/ad_clicker#26]
Hi!
Every time I'm trying to use run_in_loop.py, I've this issue.
I tried to reinstall every requirements.txt, but it's not working.
Windows 10.

![error](https://github.com/coskundeniz/ad_clicker/assets/67958671/6db417de-f659-40e7-ac0d-290f93ec9661)

Thanks a lot

**Comment by coskundeniz** [comment]
Probably, you couldn't install that package. 
Follow the instructions here: https://github.com/coskundeniz/ad_clicker/wiki/Setup-for-Windows

**Comment by HalloweenMagic** [comment]
> Probably, you couldn't install that package. Follow the instructions here: https://github.com/coskundeniz/ad_clicker/wiki/Setup-for-Windows

Thanks. I've already installaed it, but it's not working.
Also in the new release, it's not working.

**Comment by coskundeniz** [comment]
Regarding meeting for those who encounter the same issue:

- We need to manually show the path of the installed packages in run_ad_clicker.py, run_in_loop.py and proxy.py modules.
     - Add this to the start of the mentioned scripts
      `import sys`
      `sys.path.insert(0, r"full path to your site-packages folder in the project directory")`

-   Or you can look for editing the PYTHONPATH variable on Windows.
