### ISSUE TITLE
Error on Windows 11

### ISSUE THREAD

**Issue by fabiolevantino** [coskundeniz/ad_clicker#27]
Hi,
thanks for this great clicker.
I tried to use it on Windows 11, but as you can see, there are some issues.
I follow the instruction for "Windows install", and also I installaed visual-cpp-build-tools

![image](https://github.com/coskundeniz/ad_clicker/assets/140611999/eb6574a8-1758-4c21-b046-0ed8b68fee6b)

Thanks

**Comment by coskundeniz** [comment]
Hi,
Do you have Chrome installed on your system? It seems that it gives error on webdriver creation part.

**Comment by fabiolevantino** [comment]
> Hi, Do you have Chrome installed on your system? It seems that it gives error on webdriver creation part.

Yes, the last version

**Comment by coskundeniz** [comment]
Ok. Can you reserve a slot(for free) from the following link for tomorrow or later?
https://calendly.com/coskundeniz/30min
We can take a look together.

**Comment by coskundeniz** [comment]
Solved with v1.0.12
