### ISSUE TITLE
Press fix issue

### ISSUE THREAD

**Issue by inae2533** [coskundeniz/ad_clicker#29]
How to fix it
```
19-10-2023 20:32:45 <<1>> [ERROR] 204: Couldn't find latitude and longitude for 203.19.38.114! Retrying after 5 seconds...
19-10-2023 20:32:56 <<1>> [ERROR] 204: Couldn't find latitude and longitude for 203.19.38.114! Retrying after 10 seconds...
19-10-2023 20:33:21 <<1>> [ERROR] 204: Couldn't find latitude and longitude for 203.19.38.114! Retrying after 20 seconds...
19-10-2023 20:33:56 <<1>> [ERROR] 204: Couldn't find latitude and longitude for 203.19.38.114! Retrying after 40 seconds...
19-10-2023 20:34:51 <<1>> [ERROR] 204: Couldn't find latitude and longitude for 203.19.38.114! Retrying after 80 seconds...
```

![image](https://github.com/coskundeniz/ad_clicker/assets/39165832/be41d917-2fcc-46a2-a7d5-3cc155e6ca65)

**Comment by coskundeniz** [comment]
You can try with another proxy or proxy provider.

**Comment by peterkodermac** [comment]
I have the same issue. So far I have tried different providers and made sure that it's in the right format (ip:port).
I will test it on a Linux machine in the following days.

**Comment by DzergoS** [comment]
> I have the same issue. So far I have tried different providers and made sure that it's in the right format (ip:port). I will test it on a Linux machine in the following days.

how is it going?
