### ISSUE TITLE
startup without proxy in multi, queue

### ISSUE THREAD

**Issue by cetinkrt** [coskundeniz/ad_clicker#31]
Hi

multi multi and query queue all kinds of proxy wants all kinds of proxy I tried to remove it directly anyway, it says it is starting, it closes, it does not open in any way, I want to open the multi file without proxy

**Comment by coskundeniz** [comment]
It is designed in that way, so I will not change it. Without proxy using multiple browsers, you will see captcha after a few runs at best.
You are free to make a fork and change for yourself.
