### ISSUE TITLE
Problem with clicking on phone ads

### ISSUE THREAD

**Issue by Elbiss** [coskundeniz/ad_clicker#32]
I have tried multiple times, but I have noticed that call-only ads (phone) ads click is not working, and I couldn't solve this issue. Do you have a chance to release an update for this, or how can I resolve it?
Also, I am using it in run in loop mode, and I think all the processes are slow. Is there a way to speed up this?

**Comment by coskundeniz** [comment]
You can't solve it because it is running on desktop not on a mobile phone. 
> "Also, I am using it in run in loop mode, and I think all the processes are slow. Is there a way to speed up this?"
   * The goal is to make it as close as possible to human behavior.

**Comment by Elbiss** [comment]
> You can't solve it because it is running on desktop not on a mobile phone.

Let me provide an example from my own ads; usually, the number of phone calls coming from phone ad clicks does not match. In other words, I think Google Ads counts clicking on this phone as a valid click. I set all the user agents in my list to mobile, so I can see phone ads. Do you think updating it to click on phone ads would have an effect, or have you done any work on this?

**Comment by coskundeniz** [comment]
No, it is not about seeing. You can see it using a mobile user-agent but you don't have a mobile infrastructure on desktop that will trigger a call when clicked. I didn't do any work on this and I don't have a plan. Thank you.
