### ISSUE TITLE
Proxy list

### ISSUE THREAD

**Issue by J05HI** [coskundeniz/ad_clicker#34]
First of all thanks for the amazing project.
I have a little question. Which proxy list is recommended? Any free ones available which are undetected by Google?

**Comment by coskundeniz** [comment]
Free ones are used by many people and can be invalid in a short period. I recommend paid proxies. There are lots of proxy providers of course. You can check webshare, geonode, or proxyempire as example.
Thank you.

**Comment by J05HI** [comment]
> Free ones are used by many people and can be invalid in a short period. I recommend paid proxies. There are lots of proxy providers of course. You can check webshare, geonode, or proxyempire as example.
> Thank you.

Okay thanks! I'll check them.
