### ISSUE TITLE
Clicking ads not working on MacOS

### ISSUE THREAD

**Issue by J05HI** [coskundeniz/ad_clicker#35]
The click on the ads is not triggering:

[adclicker.log](https://github.com/coskundeniz/ad_clicker/files/13703665/adclicker.log)

https://github.com/coskundeniz/ad_clicker/assets/16399787/3aecc76e-9626-4bf9-a68e-65a455312991

**Comment by coskundeniz** [comment]
I can't see the video. Can you load somewhere else and give a link?

**Comment by coskundeniz** [comment]
It is the key issue for Mac. I fixed it in the premium version. You can change CONTROL with COMMAND in search_controller.py module.
