### ISSUE TITLE
All clicks are marked as invalid (ad_clicker is now detected)

### ISSUE THREAD

**Issue by Thrillium** [coskundeniz/ad_clicker#36]
Hi guys,

All clicks made by the current build of ad clicker are free, they are marked as invalid clicks in the Google Ads backend. 
Google is detecting the clicks and disregard them.

Tried 5+ different residential proxy providers.

Any idea how Google are able to detect ad_clicker?

**Comment by coskundeniz** [comment]
I think there is a problem with the underlying package undetected_chromedriver.
https://github.com/ultrafunkamsterdam/undetected-chromedriver

**Comment by J05HI** [comment]
@Thrillium 
> All clicks made by the current build of ad clicker are free

How to verify this?

@coskundeniz 
> I think there is a problem with the underlying package undetected_chromedriver

Which problem?

**Comment by coskundeniz** [comment]
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1672
