### ISSUE TITLE
Issue when running with proxy

### ISSUE THREAD

**Issue by MineClash34** [coskundeniz/ad_clicker#37]
![image](https://github.com/coskundeniz/ad_clicker/assets/54151115/07140fc0-9a48-421e-aa6a-1e1fc6df17b9)
I'm having this problem every time I try to run with a proxy, I've tried to solve it for 30 mins to no avail, can you help?

**Comment by coskundeniz** [comment]
It is not proxy related. It is coming from undetected_chromedriver package when it can't find a chromedriver.

You can go to file (...\undetected_chromedriver\patcher.py) and make the following change (just added if files check).

![Screenshot from 2024-01-09 11-41-19](https://github.com/coskundeniz/ad_clicker/assets/4516210/c1777684-0bee-416b-acfb-72b81155b978)
