### ISSUE TITLE
The localization used is not the same as the proxies I use

### ISSUE THREAD

**Issue by MineClash34** [coskundeniz/ad_clicker#38]
Hi! I hope you're well, I have an issue : I bought French proxies on WebShare (154.194.8.125 for example), but the program locates me in New York. The interface is in French though.

![image](https://github.com/coskundeniz/ad_clicker/assets/54151115/fae17ec3-f253-41c6-a136-32895a11d1ce)
![image](https://github.com/coskundeniz/ad_clicker/assets/54151115/ab7bd521-096a-4c56-b75e-a83d31751680)
![image](https://github.com/coskundeniz/ad_clicker/assets/54151115/1753c9b5-108b-476d-9f7a-e524eb40f2f3)

I've tried all sorts of things: hard-coding the latitude and longitude in the code, fiddling with a few parameters, but nothing works...

![image](https://github.com/coskundeniz/ad_clicker/assets/54151115/9bf2b861-4f93-4362-93cb-4580ff0d5e3f)
![image](https://github.com/coskundeniz/ad_clicker/assets/54151115/c5907ea5-9cd3-4eac-a7ed-9ce4ca92dffe)

I'm not sure what to try, do you have any ideas?
Thank you :)

**Comment by coskundeniz** [comment]
```
lat, long = get_location(geolocation_db_client, proxy, auth)

if lat and long:
driver.execute_cdp_cmd(
    "Emulation.setGeolocationOverride",
    {"latitude": lat, "longitude": long, "accuracy": accuracy},
)

response = requests.get(
    f"http://timezonefinder.michelfe.it/api/0_{long}_{lat}", timeout=5
)

if response.status_code == 200:
    timezone = response.json()["tz_name"]
    logger.debug(f"Timezone of {proxy.split('@')[1] if auth else proxy}: {timezone}")
        driver.execute_cdp_cmd("Emulation.setTimezoneOverride", {"timezoneId": timezone})

```

Location is set if latitude and longitude were found during IP info request. It may not be found for this one or may be found with wrong values. Please check the adclicker.log file debug logs.

**Comment by MineClash34** [comment]
Yes, I have understood that, as I said in the previous post, since by determining the latitude and longitude like that it doesn't work, I tried to hard code it directly by setting fixed coordinates (Paris coordinates), but as you can see, it still locates me in New York...


![296063638-9bf2b861-4f93-4362-93cb-4580ff0d5e3f](https://github.com/coskundeniz/ad_clicker/assets/54151115/4fadbaf2-3d39-47f6-8095-e0ad8f9a74f9)
![296063388-ab7bd521-096a-4c56-b75e-a83d31751680](https://github.com/coskundeniz/ad_clicker/assets/54151115/59e9440a-c905-44ed-85bd-22ae44bd9f4e)

**Comment by coskundeniz** [comment]
You should disable `if lat and long:` check before you try with hardcoded values. Other than that, I have no idea.

**Comment by MineClash34** [comment]
I've tried several different proxies from different providers and the problem seems to come from the WebShare proxies. I can't explain because they have a French IP but google detects them all in the USA, whether through your program or the default browsers.

**Comment by coskundeniz** [comment]
It is a possibility that their servers on the cloud are in USA and it is detected instead of actual IP location.
