### ISSUE TITLE
[Question] Premium version still undetected?

### ISSUE THREAD

**Issue by supermachine77** [coskundeniz/ad_clicker#41]
Sorry for posting this here as it's a question rather than a bug, but I couldn't find anywhere else to ask it.

Is the premium version of the tool currently fully working and undetected? I notice there was an issue before with the chromedriver causing the clicks to be detected as invalid, but has this been resolved now?

Thanks

**Comment by coskundeniz** [comment]
You could have asked via email. 
Your proxies and how clean is your machine can affect it. Some says Google sees as invalid click. Nothing changed on undetected_chromedriver package. I will add seleniumbase as an option soon for premium version.
Thank you.

**Comment by Kablonet** [comment]
Merhaba,
Yazılımı test etmek ve satın almak istiyorum. Canlı görüşebileceğimiz bir platform var mı?

iOS için Outlook<https://aka.ms/o0ukef> uygulamasını edinin
________________________________
Gönderen: Coşkun Deniz ***@***.***>
Gönderildi: Sunday, May 12, 2024 9:50:00 AM
Kime: coskundeniz/ad_clicker ***@***.***>
Bilgi: Subscribed ***@***.***>
Konu: Re: [coskundeniz/ad_clicker] [Question] Premium version still undetected? (Issue #41)


Closed #41<https://github.com/coskundeniz/ad_clicker/issues/41> as completed.

**Comment by coskundeniz** [comment]
> Merhaba, Yazılımı test etmek ve satın almak istiyorum. Canlı görüşebileceğimiz bir platform var mı?

You can test with free version. You can't test premium without buying. Currently, sales are closed to Turkey using Stripe. You can reach to email from profile.
