### ISSUE TITLE
Is there a complete installation tutorial for MAC?

### ISSUE THREAD

**Issue by kyhos** [coskundeniz/ad_clicker#44]
Is there a complete installation tutorial for MAC?
The command line commands don't work, I believe it's for Linux and I only found the link for Windows.

And to install on an online server, which one do you recommend?

**Comment by coskundeniz** [comment]
No, there is not. You can use one of AI tools to get help on that.
And to install on an online server, which one do you recommend?
    * I don't have any recommendation. You should do your own research.
