### ISSUE TITLE
getting this issue

### ISSUE THREAD

**Issue by olastech1** [coskundeniz/ad_clicker#5]
![Screenshot (15)](https://user-images.githubusercontent.com/84507555/190193286-a6e53629-fa27-4004-a345-881263b07601.png)
root@vibot:~/ad_clicker# python ad_clicker.py -q "wireless key" [-b browser] [-t ad_visit_time_in_seconds]
  File "ad_clicker.py", line 61
    logger.info(f"Connecting with IP: {response.json()['ip']}")
                                                             ^
SyntaxError: invalid syntax
root@vibot:~/ad_clicker# python ad_clicker.py -q "wireless key"
  File "ad_clicker.py", line 61
    logger.info(f"Connecting with IP: {response.json()['ip']}")
                                                             ^
SyntaxError: invalid syntax
root@vibot:~/ad_clicker#

**Comment by coskundeniz** [comment]
Of course you get an issue. You are using it wrong. [-b browser] means this parameter is optional. If you want to use it, you should use like below:

python ad_clicker.py -q "search keyword" -b chrome -t 10

**Comment by olastech1** [comment]
root@vibot:~/ad_clicker# python ad_clicker.py -q "iphhone 14" -b chrome -t 10
  File "ad_clicker.py", line 61
    logger.info(f"Connecting with IP: {response.json()['ip']}")
                                                             ^
SyntaxError: invalid syntax

still get this erro

**Comment by coskundeniz** [comment]
If you edited the code, it can be related to indentation. Please check it.
