### ISSUE TITLE
Tor search is being blocked by google.com

### ISSUE THREAD

**Issue by 5l1v3r1** [coskundeniz/ad_clicker#6]
First of all everything is working as expected but i think you missed a point 
Whenever selenium action triggered by tor proxy to open the google.com and then make the search function, everything is going through tor nodes so google naturally blocks search function with catpcha for tor node ips. Actually there is a way to bypass this like in the embedded opera vpn which disables vpn for google.com and allows the user to make the search and then during the visiting/clicking function, the vpn is activated. I am trying to find a solution as modifying the codes and will send you a pull request if i can achieve it. But do you have an idea about how to do that?

**Comment by coskundeniz** [comment]
Thanks. You can look at the setting an option to enable/disable vpn.

**Comment by zhoskhe** [comment]
hi guys im a newbie im trying to run it but it seem Im not doing it right,
Traceback (most recent call last):
  File "C:\Users\CO\documents\ad_clicker\ad_clicker.py", line 76, in <module>
    main()
  File "C:\Users\CO\documents\ad_clicker\ad_clicker.py", line 58, in main
    change_ip_address(password)
  File "C:\Users\CO\documents\ad_clicker\ad_clicker.py", line 22, in change_ip_address
    controller.authenticate(password=password)
  File "C:\Users\CO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\stem\control.py", line 1112, in authenticate
    stem.connection.authenticate(self, *args, **kwargs)
  File "C:\Users\CO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\stem\connection.py", line 629, in authenticate
    raise auth_exc
  File "C:\Users\CO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\stem\connection.py", line 583, in authenticate
    authenticate_password(controller, password, False)
  File "C:\Users\CO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\stem\connection.py", line 739, in authenticate_password
    raise IncorrectPassword(str(auth_response), auth_response)
stem.connection.IncorrectPassword: Authentication failed: Password did not match HashedControlPassword value from configuration

**Comment by 5l1v3r1** [comment]
ok function like opera embedded vpn is done, now google cannot block anything and also i added several useragents as mobile, the good thing that there is undetected chromium driver which helped me a lot through the process regardless the vpn bypass function. Next thing to add gui support.

**Comment by 5l1v3r1** [comment]
I also made a headless version for the spoofed servers to do mass actions.

**Comment by 5l1v3r1** [comment]
> hi guys im a newbie im trying to run it but it seem Im not doing it right, Traceback (most recent call last): File "C:\Users\CO\documents\ad_clicker\ad_clicker.py", line 76, in main() File "C:\Users\CO\documents\ad_clicker\ad_clicker.py", line 58, in main change_ip_address(password) File "C:\Users\CO\documents\ad_clicker\ad_clicker.py", line 22, in change_ip_address controller.authenticate(password=password) File "C:\Users\CO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\stem\control.py", line 1112, in authenticate stem.connection.authenticate(self, *args, **kwargs) File "C:\Users\CO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\stem\connection.py", line 629, in authenticate raise auth_exc File "C:\Users\CO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\stem\connection.py", line 583, in authenticate authenticate_password(controller, password, False) File "C:\Users\CO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\stem\connection.py", line 739, in authenticate_password raise IncorrectPassword(str(auth_response), auth_response) stem.connection.IncorrectPassword: Authentication failed: Password did not match HashedControlPassword value from configuration

your privoxy setup is not ok, you need to run the installation script from the beginning and the password generation must be done to authenticate. By the way if you use zsh instead of bash, you can modify the script accordingly.

**Comment by coskundeniz** [comment]
> > hi guys im a newbie im trying to run it but it seem Im not doing it right, Traceback (most recent call last): File "C:\Users\CO\documents\ad_clicker\ad_clicker.py", line 76, in main() File "C:\Users\CO\documents\ad_clicker\ad_clicker.py", line 58, in main change_ip_address(password) File "C:\Users\CO\documents\ad_clicker\ad_clicker.py", line 22, in change_ip_address controller.authenticate(password=password) File "C:\Users\CO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\stem\control.py", line 1112, in authenticate stem.connection.authenticate(self, *args, **kwargs) File "C:\Users\CO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\stem\connection.py", line 629, in authenticate raise auth_exc File "C:\Users\CO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\stem\connection.py", line 583, in authenticate authenticate_password(controller, password, False) File "C:\Users\CO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\stem\connection.py", line 739, in authenticate_password raise IncorrectPassword(str(auth_response), auth_response) stem.connection.IncorrectPassword: Authentication failed: Password did not match HashedControlPassword value from configuration
> 
> your privoxy setup is not ok, you need to run the installation script from the beginning and the password generation must be done to authenticate. By the way if you use zsh instead of bash, you can modify the script accordingly.

Also, keep in mind that the setup script is for Linux. It seems you are using Windows.

**Comment by coskundeniz** [comment]
> ok function like opera embedded vpn is done, now google cannot block anything and also i added several useragents as mobile, the good thing that there is undetected chromium driver which helped me a lot through the process regardless the vpn bypass function. Next thing to add gui support.

Thanks. 
I am not a fun of UIs, so you can either keep it in your own branch or send as a separate branch.

**Comment by coskundeniz** [comment]
> I also made a headless version for the spoofed servers to do mass actions.

This uses the webdriver-setup package which is also written by me and it supports passing options. You can add it as an optional argument(-hl, --headless) and pass it to `get_webdriver_for` call in `SearchController` class.

**Comment by 5l1v3r1** [comment]
> > ok function like opera embedded vpn is done, now google cannot block anything and also i added several useragents as mobile, the good thing that there is undetected chromium driver which helped me a lot through the process regardless the vpn bypass function. Next thing to add gui support.
> 
> Thanks. I am not a fun of UIs, so you can either keep it in your own branch or send as a separate branch.

i thank you for such a great tool

**Comment by coskundeniz** [comment]
Since the version with Tor is not the main branch, I am closing this.
