### ISSUE TITLE
the problem with type tuple

### ISSUE THREAD

**Issue by lvwuwei** [coskundeniz/ad_clicker#7]
(env) root@e86cd3ba226b:~/ad_clicker# python ad_clicker.py -q "byy3"
Traceback (most recent call last):
  File "ad_clicker.py", line 4, in <module>
    from search_controller import SearchController
  File "/root/ad_clicker/search_controller.py", line 18, in <module>
    AdList = list[tuple[selenium.webdriver.remote.webelement.WebElement, int]]
TypeError: 'type' object is not subscriptable

**Comment by coskundeniz** [comment]
If your Python version is less than 3.9 update import like below
from typing import List, Tuple

and use like below
List[Tuple[selenium.webdriver.remote.webelement.WebElement, int]]

**Comment by coskundeniz** [comment]
.

**Comment by lvwuwei** [comment]
Anyway, I am very happy to receive your reply and technical support in the first time. I am very happy to study with you,
after,update the python version with python3.9 ,show problem?   i think  allow cookie?
24-10-2022 11:39:36 [ INFO]  57: Starting search for 'xxxxx.com'
Traceback (most recent call last):
  File "/root/ad_clicker/ad_clicker.py", line 53, in <module>
    main()
  File "/root/ad_clicker/ad_clicker.py", line 41, in main
    ads = search_controller.search_for_ads()
  File "/root/ad_clicker/search_controller.py", line 60, in search_for_ads
    search_input_box.send_keys(self._search_query, Keys.ENTER)
  File "/root/ad_clicker/env/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 223, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "/root/ad_clicker/env/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 396, in _execute
    return self._parent.execute(command, params)
  File "/root/ad_clicker/env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/root/ad_clicker/env/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=106.0.5249.119)
Stacktrace:
#0 0x5629805912c3 <unknown>
#1 0x56298039a700 <unknown>
#2 0x5629803cdd1e <unknown>
#3 0x5629803cd2c4 <unknown>
#4 0x5629803f1f42 <unknown>
#5 0x5629803c8073 <unknown>
#6 0x5629803f20ae <unknown>
#7 0x562980409a50 <unknown>
#8 0x5629803f1d63 <unknown>
#9 0x5629803c67e3 <unknown>
#10 0x5629803c7a21 <unknown>
#11 0x5629805df18e <unknown>
#12 0x5629805e2622 <unknown>
#13 0x5629805c5aae <unknown>
#14 0x5629805e32a3 <unknown>
#15 0x5629805b9ecf <unknown>
#16 0x562980603588 <unknown>
#17 0x562980603706 <unknown>
#18 0x56298061d8b2 <unknown>
#19 0x7f72e6d25609 <unknown>

**Comment by coskundeniz** [comment]
> Anyway, I am very happy to receive your reply and technical support in the first time. I am very happy to study with you, after,update the python version with python3.9 ,show problem? i think allow cookie? 24-10-2022 11:39:36 [ INFO] 57: Starting search for 'xxxxx.com' Traceback (most recent call last): File "/root/ad_clicker/ad_clicker.py", line 53, in main() File "/root/ad_clicker/ad_clicker.py", line 41, in main ads = search_controller.search_for_ads() File "/root/ad_clicker/search_controller.py", line 60, in search_for_ads search_input_box.send_keys(self._search_query, Keys.ENTER) File "/root/ad_clicker/env/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 223, in send_keys self._execute(Command.SEND_KEYS_TO_ELEMENT, File "/root/ad_clicker/env/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 396, in _execute return self._parent.execute(command, params) File "/root/ad_clicker/env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute self.error_handler.check_response(response) File "/root/ad_clicker/env/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable (Session info: chrome=106.0.5249.119) Stacktrace: #0 0x5629805912c3 #1 0x56298039a700 #2 0x5629803cdd1e #3 0x5629803cd2c4 #4 0x5629803f1f42 #5 0x5629803c8073 #6 0x5629803f20ae #7 0x562980409a50 #8 0x5629803f1d63 #9 0x5629803c67e3 #10 0x5629803c7a21 #11 0x5629805df18e #12 0x5629805e2622 #13 0x5629805c5aae #14 0x5629805e32a3 #15 0x5629805b9ecf #16 0x562980603588 #17 0x562980603706 #18 0x56298061d8b2 #19 0x7f72e6d25609

The below commit is the solution for that but in the old_version branch
https://github.com/coskundeniz/ad_clicker/commit/e56095362c40b53ee19311afd4a91b15e43d2b17

I can merge it to main sometime in the future.

Thanks.
