### ISSUE TITLE
Exclude specific domain

### ISSUE THREAD

**Issue by HalloweenMagic** [coskundeniz/ad_clicker#9]
Is it possible to exclude a specific domain to the clicker?

**Comment by coskundeniz** [comment]
No, but you can include by filtering feature. Usage explained in the examples.

* Search for "wireless speaker" and click links that include the given filter words in url or title.

    python ad_clicker.py -q "wireless speaker@amazon#ebay  # mediamarkt"

    Spaces around "@" and "#" are ignored, so both "wireless speaker@amazon#ebay" and "wireless speaker @ amazon # ebay" take "wireless speaker" as search query and "amazon" and "ebay" as filter words.
